# Ewellix Actuator Status

# Complete status as byte
uint8 code

# Drive unavailable/available
bool available

# Signal limit_in_out inactive/active
bool limit_in_out

# Signal switch 1 inactive/active
bool switch1

# Signal switch 2 inactive/active
bool switch2

# Motion inactive/active
bool motion

# In position not reached/reached
bool reached

# Out position
bool out_position

# Stoke not done/done
bool stroke
