# Ewellix Serial send message and receive response

# Commands:
uint8 COMMAND_GET=0x47
uint8 COMMAND_TRANSER=0x54
uint8 COMMAND_CYCLIC=0x43
uint8 COMMAND_EXECUTE=0x45
uint8 COMMAND_STOP=0x53
uint8 COMMAND_OPEN=0x4F
uint8 COMMAND_ABORT=0x41

# Data Fields
uint16 DF_FIRMWARE=0x0001
uint16 DF_CONFIGURATION=0x0002
uint16 DF_ACTUAL_POSITION_ALL=0x0010
uint16 DF_ACTUAL_POSITION_ACTUATOR=0x0011
uint16 DF_ACTUAL_STATE_BINARY=0x0020
uint16 DF_ACTUAL_STATE_ANALOG=0x0030
uint16 DF_ACTUAL_STATE_KEYS=0x0040
uint16 DF_NUMBER_CYCLE_IN_ALL=0x0060
uint16 DF_NUMBER_CYCLE_IN_ACTUATOR=0x0061
uint16 DF_NUMBER_CYCLE_OUT_ALL=0x0070
uint16 DF_NUMBER_CYCLE_OUT_ACTUATOR=0x0071
uint16 DF_NUMBER_ERROR_ALL=0x0080
uint16 DF_NUMBER_ERROR_ACTUATOR=0x0081
uint16 DF_NUMBER_TOTAL_OVER_CURRENT=0x008F
uint16 DF_CUMULATED_STROKE=0x0090
uint16 DF_CUMULATED_STROKE_ACTUATOR=0x0091
uint16 DF_CURRENT_ALL=0x00A0
uint16 DF_CURRENT_ACTUATOR=0x00A1
uint16 DF_MAX_CURRENT_ALL=0x00B0
uint16 DF_MAX_CURRENT_ACTUATOR=0x00B1
uint16 DF_MAX_TOTAL_CURRENT=0x00BF
uint16 DF_MAX_TEMP_RECTIFIER=0x00C0
uint16 DF_OVER_TEMP_RECTIFIER=0x00C1
uint16 DF_ERROR_CODE_HISTORY=0x00D0
uint16 DF_STATUS_2_ALL=0x00E0
uint16 DF_STATUS_2_ACTUATOR=0x00E1
uint16 DF_SPEED_ALL=0x00F0
uint16 DF_SPEED_ACTUATOR=0x00F1
uint16 DF_BATTERY_MAINS=0x0100
uint16 DF_BINARY_OUTPUT_STATUS=0x0110
uint16 DF_LED_HS=0x0120
uint16 DF_LED_LB=0x0130
uint16 DF_BUZZER=0x0140
uint16 DF_SENSOR_SUPPLY=0x0150
uint16 DF_LOCK_STATUS=0x0162
uint16 DF_BATTERY_VOLTAGE=0x0164
uint16 DF_LOCKING_BOX_DETECTED=0x0165
uint16 DF_USER=0x0166
uint16 DF_STATUS_1_ALL=0x0170
uint16 DF_STATUS_1_ACTUATOR=0x0171
uint16 DF_CONVERSION_FACTOR_ALL=0x1010
uint16 DF_CONVERSION_FACTOR_ACTUATOR=0x1011
uint16 DF_USER_POSITION_ALL=0x2000
uint16 DF_USER_POSITION_ACTUATOR=0x2001

# Writable Data Fields
uint16 WDF_CYCLIC_OBJECT=0x3001
uint16 WDF_REMOTE_SPEED_ALL=0x3010
uint16 WDF_REMOTE_SPEED_FUNCTION=0x301A
uint16 WDF_REMOTE_POSITION_ALL=0x3020
uint16 WDF_REMOTE_POSITION_ACTUATOR=0x3021

# Executable Functions
uint8 EF_NO_MOTION=0
uint8 EF_IN=1
uint8 EF_OUT=2
uint8 EF_MEM1=3
uint8 EF_MEM2=4
uint8 EF_MEM3=5
uint8 EF_MEM4=6
uint8 EF_INTERMEDIATE_IN=7
uint8 EF_INTERMEDIATE_OUT=8
uint8 EF_REMOTE_POSITION=9

---
bool success

